### ISSUE TITLE
Includes problem

### ISSUE THREAD

**Issue by MAGNAT2645** [Timocop/BasicPawn#19] opened 2018-08-23 14:07 UTC
Why BasicPawn doesn't include non-core includes like tf2.inc, tf2_stocks.inc, sdktools.inc, sdkhooks.inc and etc.?

I've set config to Manual and put include directory but tooltip doesn't popup for non-core SM natives.
Also all non-core includes doesn't displaying in Object Browser.

**Comment by Timocop** [comment] 2018-08-23 14:49
It does, you just have to include them in your source. The Object Browser only shows what you have included (recursively through includes). sourcemod.inc is always included by default like the compiler does.
If you want to know all available includes just write `#include` and it will show all includes BasicPawn has found.

![](https://i.imgur.com/O65IbxG.gif)

**Comment by MAGNAT2645** [comment] 2018-08-23 15:43
I thought that includes will be stored globally and user will see all content inside include folder.
Also tooltip doesn't work for separated code parts like **#include 2nd_part_of_code.sp**. I mean that my includes are visible only inside main SP that i will compile, but other parts can't see all **#include** from this file.

**Comment by MAGNAT2645** [comment] 2018-08-23 15:58
Also would be good if there was hotkeys like **Ctrl+R** for **Format Code > Reindent Code** (and without need to select where to do it).

**Comment by Timocop** [comment] 2018-08-23 20:54
Yea you have to put <> (include) or "" (relative path) around the filename/path in order for it to work correctly, nice catch. Ill fix that.

Could you open another issue for the Format Code request since its off-topic.

Also, if youre working with includes, always keep the main source open. So BasicPawn knows which files are references where. Example:
![](https://i.imgur.com/tOC1mqH.gif)

**Comment by MAGNAT2645** [comment] 2018-08-23 21:35
Yeah, now it works. Would be good if there was support for #include preprocessor without <> and "".
I will open new issue with 2 other bugs (as i think).

**Comment by Timocop** [comment] 2018-08-23 21:48
Already on my todo list.
Just make a new issue for your Format Code request. This issue will be related to the #include issue so i can close this when the issue is fixed.

**Comment by Timocop** [comment] 2018-08-23 22:00
Fixed. Thank you for reporting it :)

**Closed by Timocop** 2018-08-23 22:00 UTC
Labels: bug, question
