### ISSUE TITLE
Unexpected exception on fast typing?

### ISSUE THREAD

**Issue by GAMMACASE** [Timocop/BasicPawn#78] opened 2020-08-06 18:30 UTC
Wasn't really "fast" typing, but yea, was doing it quick enough I guess. Didn't do anything unusual, was just typing.
The exception here says "Index Out of Bounds Exception":
![image](https://user-images.githubusercontent.com/31375974/89568315-ca73c700-d82b-11ea-9cd1-e6d1de31d33c.png)

Edit: figured the pic isn't very useful, but I'm not really able to reproduce it, as I said, all I did was just typing. Maybe you have any clue on why that might've happened idk.

**Comment by Timocop** [comment] 2020-08-06 19:37
Thank for reporting the issue!
I may know where the problem is.
Are you able to attach your ``application_error.log`` file (Located in the BasicPawn folder)?
This may help in this case.

**Comment by GAMMACASE** [comment] 2020-08-06 19:43
Here's all I've got in that file for today: (Text here saying same thing as in original pic)
```
[06.08.2020 21:31:05]
System.IndexOutOfRangeException: Индекс находился вне границ массива.
   в BasicPawn.ClassTabControl.ClassTab.ClassScopeHighlighting.FindScopeLocation(ClassSyntaxSourceAnalysis mSourceAnalysis, Int32 iCaretOffset, Boolean bCaretAfter, Point& r_ScopeLocation)
   в BasicPawn.ClassBackgroundUpdater.UpdateScopeHighlighting(ClassTab mActiveTab, Int32 iCaretOffset)
   в BasicPawn.ClassBackgroundUpdater.BackgroundThread()
```

I can send you the whole file if this isn't enough, but I would like to take it to dms then, I hope you don't mind it.

**Comment by Timocop** [comment] 2020-08-07 11:25
This should be fixed now. If this issue still persists, reopen this issue again please.

**Closed by Timocop** 2020-08-07 11:25 UTC
Labels: bug
