### ISSUE TITLE
[Bug] Compiler Window Freeze

### ISSUE THREAD

**Issue by MAGNAT2645** [Timocop/BasicPawn#61] opened 2019-05-12 05:09 UTC
![изображение](https://user-images.githubusercontent.com/11666918/57578030-c7a9eb00-749d-11e9-83d2-96076b63d3a5.png)

Window just freezes BUT BasicPawn still running fine.
Checked all configs for compiler paths and it was fine.
This happened with new v0.831

**Comment by MAGNAT2645** [comment] 2019-05-12 05:13
Hmm, i've commented morecolors.inc and this bug disappeared.

**Comment by MAGNAT2645** [comment] 2019-05-12 05:15
This bug appears with this [multicolors](https://github.com/Bara/Multi-Colors/blob/master/addons/sourcemod/scripting/include/multicolors.inc)

**Comment by MAGNAT2645** [comment] 2019-05-12 06:24
Nevermind, fixed that. Just put this:
`#define MC_LoopClients(%1)		for ( int %1 = 1; %1 <= MaxClients; %1++ )`

**Comment by Timocop** [comment] 2019-05-12 15:22
Im unable to reproduce this. Ive downloaded multicolors and its testcase. The testcase compiled fine and the windows disappeared.

Can you post what you did to make this happen and also can you post the `applocation_error.log` and sources?

**Comment by Timocop** [comment] 2019-05-12 16:02
Nevermind, i reproduced it. Seems like the compiler process get 'stuck' for some reason when commenting out `MuCo_LoopClients` define. Ill reopen this and create some compiler timeout or cancel button for this issue. So the user doesnt get stuck when the compiler process is hanging.

If this happens again open `Task Manager` and kill the `spcomp.exe` process.

**Comment by Timocop** [comment] 2019-05-12 18:19
Fixed in 3a57dc359e6a5be83e36f92171cb0f9e1b1e5846

**Closed by Timocop** 2019-05-12 18:19 UTC
Labels: bug
